version: '3.8'

services:
  airflow_db:
    image: postgres:16
    container_name: airflow_db
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    ports:
      - 55434:5432
    volumes:
      - ./airflow_db:/var/lib/postgresql/data
    restart: always

  airflow_webserver:
    image: apache/airflow:2.11.0
    container_name: airflow_webserver
    depends_on:
      - airflow_db
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@airflow_db:5432/airflow
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - AIRFLOW__WEBSERVER__DEFAULT_UI_TIMEZONE=America/Sao_Paulo
      - _PIP_ADDITIONAL_REQUIREMENTS=apache-airflow-providers-google pandas pyarrow kaggle
      - GOOGLE_APPLICATION_CREDENTIALS=/opt/airflow/credentials/google_credentials.json
      - KAGGLE_USERNAME=${KAGGLE_USERNAME}
      - KAGGLE_KEY=${KAGGLE_KEY}
    ports:
      - "8080:8080"
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
      - ../data:/opt/airflow/data
      - ~/.google/credentials:/opt/airflow/credentials:ro
    command: webserver
    restart: always

  airflow_scheduler:
    image: apache/airflow:2.11.0
    container_name: airflow_scheduler
    depends_on:
      - airflow_db
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@airflow_db:5432/airflow
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - _PIP_ADDITIONAL_REQUIREMENTS=apache-airflow-providers-google pandas pyarrow kaggle
      - GOOGLE_APPLICATION_CREDENTIALS=/opt/airflow/credentials/google_credentials.json
      - KAGGLE_USERNAME=${KAGGLE_USERNAME}
      - KAGGLE_KEY=${KAGGLE_KEY}
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
      - ../data:/opt/airflow/data
      - ~/.google/credentials:/opt/airflow/credentials:ro
    command: scheduler
    restart: always